openapi: 3.0.1
info:
  title: ChatGPT Archive Utility API
  version: "0.1.0"
paths:
  /archives:
    post:
      summary: Create an archive from uploaded ChatGPT export
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                title:
                  type: string
      responses:
        '201':
          description: Archive created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Archive'
  /archives/{id}:
    get:
      summary: Get archive by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Archive
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Archive'
    delete:
      summary: Delete archive
      responses:
        '204':
          description: Deleted
  /search:
    get:
      summary: Search user archives
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: startDate
          schema:
            type: string
            format: date
        - in: query
          name: endDate
          schema:
            type: string
            format: date
      responses:
        '200':
          description: search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Archive'
  /api/clerk/webhook:
    post:
      summary: Handle Clerk webhook events
      operationId: handleClerkWebhook
      parameters:
        - in: header
          name: svix-signature
          required: true
          schema:
            type: string
            description: Webhook signature for verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClerkWebhookEvent'
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Invalid signature
        '400':
          description: Invalid request
components:
  schemas:
    Archive:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        title:
          type: string
        content:
          type: string
        attachments:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              size:
                type: integer
              contentType:
                type: string
              url:
                type: string
              checksum:
                type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ClerkWebhookEvent:
      type: object
      required:
        - type
        - data
        - object
        - evt_id
      properties:
        type:
          type: string
          description: Event type (e.g., user.created, user.deleted)
        data:
          oneOf:
            - $ref: '#/components/schemas/ClerkUser'
            - type: object
        object:
          type: string
          enum: [event]
        evt_id:
          type: string
    ClerkUser:
      type: object
      required:
        - id
        - email_addresses
        - created_at
      properties:
        id:
          type: string
          description: Clerk user ID
        email_addresses:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              email_address:
                type: string
              verification:
                type: object
        first_name:
          type: string
        last_name:
          type: string
        created_at:
          type: integer
          description: Unix timestamp
        updated_at:
          type: integer
          description: Unix timestamp
